services:
  # solr:
  #   build: .
  #   volumes:
  #     - /mnt/c/Users/Tyler/Desktop/PV:/app/data
  #   command: tail -f /dev/null
  qgis:
    build: .
    volumes:
      - /mnt/c/Users/Tyler/Desktop/PV:/app/data
    command: tail -f /dev/null
